
- name: Setup Adminer
  hosts: all
  roles:
    - role: geerlingguy.postgresql
    - role: geerlingguy.apache
    - role: geerlingguy.php
      tags: php
    - role: local.adminer
      tags: adminer
